/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TechQuizApp.gui;

import TechQuizApp.pojo.UserProfile;
import static TechQuizApp.pojo.UserProfile.getUsername;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class AdminOptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminOptionFrame1
     */
    public AdminOptionFrame() {
        initComponents();

        setLocationRelativeTo(null);
        setTitle("THE QUIZZ APP");
        lblusername3.setText("Hello "+UserProfile.getUsername());       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jrbsetpaper = new javax.swing.JRadioButton();
        jrbeditpaper = new javax.swing.JRadioButton();
        jrbregisterstudent = new javax.swing.JRadioButton();
        jrbviewscores = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btndotask = new javax.swing.JButton();
        lblusername3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("STZhongsong", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText(" ONLINE QUIZ ADMINISTRATION  PANEL");

        lbllogout.setBackground(new java.awt.Color(0, 0, 0));
        lbllogout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbllogout.setForeground(new java.awt.Color(255, 153, 0));
        lbllogout.setText("Logout");
        lbllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllogoutMouseExited(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Make A Choice");

        jrbsetpaper.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbsetpaper);
        jrbsetpaper.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbsetpaper.setForeground(new java.awt.Color(255, 102, 0));
        jrbsetpaper.setText("Set A Paper");

        jrbeditpaper.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbeditpaper);
        jrbeditpaper.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbeditpaper.setForeground(new java.awt.Color(255, 102, 0));
        jrbeditpaper.setText("Edit Paper");
        jrbeditpaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbeditpaperActionPerformed(evt);
            }
        });

        jrbregisterstudent.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbregisterstudent);
        jrbregisterstudent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbregisterstudent.setForeground(new java.awt.Color(255, 102, 0));
        jrbregisterstudent.setText("Register Student");

        jrbviewscores.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbviewscores);
        jrbviewscores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbviewscores.setForeground(new java.awt.Color(255, 102, 0));
        jrbviewscores.setText("View Scores");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\OneDrive\\Pictures\\Camera Roll\\admin.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        btndotask.setBackground(new java.awt.Color(0, 0, 0));
        btndotask.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btndotask.setForeground(new java.awt.Color(255, 102, 0));
        btndotask.setText("Do Task");
        btndotask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndotaskActionPerformed(evt);
            }
        });

        lblusername3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblusername3.setForeground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblusername3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(559, Short.MAX_VALUE)
                .addComponent(btndotask, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(442, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jrbviewscores)
                        .addComponent(jrbregisterstudent)
                        .addComponent(jrbeditpaper)
                        .addComponent(jrbsetpaper)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(358, 358, 358)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblusername3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(165, 165, 165)
                .addComponent(btndotask)
                .addGap(111, 111, 111))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(223, 223, 223)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(42, 42, 42)
                    .addComponent(jrbsetpaper)
                    .addGap(56, 56, 56)
                    .addComponent(jrbeditpaper)
                    .addGap(45, 45, 45)
                    .addComponent(jrbregisterstudent)
                    .addGap(46, 46, 46)
                    .addComponent(jrbviewscores)
                    .addContainerGap(231, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseClicked
        LoginFrame loginframe=new LoginFrame();
        loginframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbllogoutMouseClicked

    private void lbllogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseEntered
        lbllogout.setForeground(Color.white);

    }//GEN-LAST:event_lbllogoutMouseEntered

    private void lbllogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseExited
        lbllogout.setForeground( new Color(255,153,0));
    }//GEN-LAST:event_lbllogoutMouseExited

    private void btndotaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndotaskActionPerformed
        if(jrbsetpaper.isSelected())
        {
            SetPaperFrame fr=new SetPaperFrame();
            fr.setVisible(true);
        }
        else if(jrbeditpaper.isSelected())
        {
            EditPaperFrame fe=new EditPaperFrame();
            fe.setVisible(true);
        }

        else if(jrbregisterstudent.isSelected())
        {
            RegisterStudentFrame re=new  RegisterStudentFrame();
            re.setVisible(true);

        }

        else if(jrbviewscores.isSelected())
        {
            ViewScoresFrame vr=new ViewScoresFrame();
            vr.setVisible(true);
        }

        else
        {
            JOptionPane.showMessageDialog(null,"Plese make Selection!1","No Selection!!",JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.dispose();
    }//GEN-LAST:event_btndotaskActionPerformed

    private void jrbeditpaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbeditpaperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbeditpaperActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndotask;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbeditpaper;
    private javax.swing.JRadioButton jrbregisterstudent;
    private javax.swing.JRadioButton jrbsetpaper;
    private javax.swing.JRadioButton jrbviewscores;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lblusername3;
    // End of variables declaration//GEN-END:variables
}
